name: Access Private Repository File

on:
  push:
    branches: "*"

jobs:
  access_file_job:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout main repository
      uses: actions/checkout@v2

    - name: Checkout private repository
      uses: actions/checkout@v2
      with:
        repository: anas203044/private-test
        ref: main
        token: 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

    - name: Print file contents
      run: cat action.yml
