name: Access Private Repository File

on:
  push:
    branches: [main]

jobs:
  access_file_job:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout main repository
      uses: actions/checkout@v2

    - name: Checkout private repository
      uses: actions/checkout@v2
      with:
        repository: anas203044/private-test
        ref: main
        token: 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

    - name: Print file contents
      run: cat action.yml
