name: Build
on:
  push:
    branches:
      - master # or the name of your main branch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Create SonarQube project
        env:
          SONARQUBE_URL: http://54.73.70.164:9000
          SONARQUBE_TOKEN: sqa_f658ef5fbb92484d00c5b2331c21cfe09830404e
        run: |
          curl -s -X POST -H "Authorization: Bearer $SONARQUBE_TOKEN" -H "Content-Type: application/json" -d '{"name":"test", "project":"testsonar3"}' "$SONARQUBE_URL/api/projects/create"
      
      - name: Create SonarQube properties file
        run: echo "sonar.projectKey=testsonar" > sonar-project.properties

      
      - name: Echo secret value
        env:
          value: ${{ vars.anas }}
        run: |
          echo $value
          echo ${{ env.value }}
          echo ${{ vars.value }}
          echo ${{ secrets.value }}
          pwd
