name: Build
on:
  push:
    branches:
      - master # or the name of your main branch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Create SonarQube project
        env:
          SONARQUBE_URL: http://54.73.70.164:9000
          SONARQUBE_TOKEN: squ_92ce500b4383353ef21219293c07ffff35128a09
          SONAR_PROJECT_KEY: sonartest5
        run: |
          echo $SONARQUBE_URL
          echo $SONARQUBE_TOKEN
          echo $SONAR_PROJECT_KEY
          curl --include --request POST -u $SONARQUBE_TOKEN: '$SONARQUBE_URL/api/projects/create?name=$SONAR_PROJECT_KEY&project=$SONAR_PROJECT_KEY'
      
      - name: Create SonarQube properties file
        run: echo "sonar.projectKey=testsonar" > sonar-project.properties

      
      - name: Echo secret value
        env:
          value: ${{ vars.anas }}
        run: |
          echo $value
          echo ${{ env.value }}
          echo ${{ vars.value }}
          echo ${{ secrets.value }}
          pwd
